apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: edc-v
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:wal2json
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "controlplane"
        - name: POSTGRES_USER
          value: "cp"
        - name: POSTGRES_PASSWORD
          value: "cp"
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: edc-v
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: edc-v
data:
  init.sql: |
    CREATE DATABASE identityhub;
    CREATE USER ih WITH PASSWORD 'ih';
    GRANT ALL PRIVILEGES ON DATABASE identityhub TO ih;
    \c identityhub
    GRANT ALL ON SCHEMA public TO ih;
        
    CREATE DATABASE issuerservice;
    CREATE USER issuer WITH PASSWORD 'issuer';
    GRANT ALL PRIVILEGES ON DATABASE issuerservice TO issuer;
    \c issuerservice
    GRANT ALL ON SCHEMA public TO issuer;